name: buildAndPublishLibrary

on:
  push:
    tags:
      - 'v*'
      - '!v*beta*'

jobs:
  publish:
    name: buildLibrary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js v16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 'v16.14.0'

      - name: Install
        run: npm install -g pnpm && pnpm install --force

      - name: Build
        run: npm run build:rollup

      - name: Publish to NPM
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.PUBLISH }}
